name: events_emitter
description: An intuitive Event-based system, inspired by NodeJS's Event Emitter. Allows for multiple data types with type safety. Based on JavaScript and suitable for Dart and Flutter.
version: 0.0.7
homepage: https://github.com/DrafaKiller/EventEmitter-dart

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"