name: events_emitter
description: An intuitive Event-based system, inspired by NodeJS's Event Emitter. Allows for multiple data types with type safety events. Based on JavaScript and suitable for Dart and Flutter.
version: 0.4.5
repository: https://github.com/DrafaKiller/EventEmitter-dart
homepage: https://github.com/DrafaKiller/EventEmitter-dart

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  rxdart: ^0.27.5
  
dev_dependencies: 
  lint: ^1.10.0
